/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if _MSC_VER
#pragma pack (push,4)
#endif

#ifndef SERVERCRASHFIX_V11_API
#define SERVERCRASHFIX_V11_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern SERVERCRASHFIX_V11_API FName SERVERCRASHFIX_V11_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


class SERVERCRASHFIX_V11_API ASCFNative : public AActor
{
public:
    class ASCFActor* fixActor;
    class ASCFSpec* fixSpec;
    BITFIELD bDLOHooked:1 GCC_PACK(4);
    BITFIELD bNetHooked:1;
    BITFIELD bExecHooked:1;
    BITFIELD bMallocHooked:1;
    BITFIELD bHandlersInstalled:1;
    FStringNoInit AffinitySet GCC_PACK(4);
    BITFIELD bTimerSet:1 GCC_PACK(4);
    BITFIELD bAppSecondsHooked:1;
    DECLARE_FUNCTION(execHookAppSeconds);
    DECLARE_FUNCTION(execRequestTimer);
    DECLARE_FUNCTION(execSetAffinity);
    DECLARE_FUNCTION(execInstallHandlers);
    DECLARE_FUNCTION(execGetPlatform);
    DECLARE_FUNCTION(execHookMalloc);
    DECLARE_FUNCTION(execUnHookExec);
    DECLARE_FUNCTION(execHookExec);
    DECLARE_FUNCTION(execUnHookNet);
    DECLARE_FUNCTION(execHookNet);
    DECLARE_FUNCTION(execUnHookDLO);
    DECLARE_FUNCTION(execHookDLO);
    DECLARE_CLASS(ASCFNative,AActor,0,ServerCrashFix_v11)
    NO_DEFAULT_CONSTRUCTOR(ASCFNative)
};

#endif

AUTOGENERATE_FUNCTION(ASCFNative,-1,execHookAppSeconds);
AUTOGENERATE_FUNCTION(ASCFNative,-1,execRequestTimer);
AUTOGENERATE_FUNCTION(ASCFNative,-1,execSetAffinity);
AUTOGENERATE_FUNCTION(ASCFNative,-1,execInstallHandlers);
AUTOGENERATE_FUNCTION(ASCFNative,-1,execGetPlatform);
AUTOGENERATE_FUNCTION(ASCFNative,-1,execHookMalloc);
AUTOGENERATE_FUNCTION(ASCFNative,-1,execUnHookExec);
AUTOGENERATE_FUNCTION(ASCFNative,-1,execHookExec);
AUTOGENERATE_FUNCTION(ASCFNative,-1,execUnHookNet);
AUTOGENERATE_FUNCTION(ASCFNative,-1,execHookNet);
AUTOGENERATE_FUNCTION(ASCFNative,-1,execUnHookDLO);
AUTOGENERATE_FUNCTION(ASCFNative,-1,execHookDLO);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif NAMES_ONLY

#if _MSC_VER
#pragma pack (pop)
#endif
